###
GRPC localhost:8101/parts.PartsService/ReceivePart

{
  "partId": "logical-part-id-22",
  "partName": "a cool part 7",
  "partWeight": 10,
  "references": [
    "referenced-part-id-3",
    "referenced-part-id-4"
  ]
}